import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import localFont from 'next/font/local'
import './globals.css'

import Image from 'next/image'
import Link from 'next/link'
import poke from '@/public/images/poke.png'

import AudioPlayer from '@/components/audioplayer'

const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-roboto'
})

const geistHollow = localFont({
  src: './fonts/Pokemon Hollow.ttf',
  variable: '--font-geist-sans',
  weight: '100 900'
})

const geistSolid = localFont({
  src: './fonts/Pokemon Solid.ttf',
  variable: '--font-geist-sans2',
  weight: '100 900'
})

export const metadata: Metadata = {
  title: 'Pokedex',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${geistHollow.variable} ${geistSolid.variable} antialiased bg-black w-screen p-0 m-0 box-border font-roboto`}
      >
        <div className="mt-8 mb-16 ml-8 flex items-center">
          <Link href="/">
            <Image src={poke} width={230} alt="PokemonAPI logo"></Image>
          </Link>
          <AudioPlayer></AudioPlayer>
        </div>
        {children}
      </body>
    </html>
  )
}
