import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'

// Importando a fonte Roboto do Google
const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'], 
  variable: '--font-roboto', 
})

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} antialiased bg-black w-screen p-0 m-0 box-border font-roboto`}
      >
        {children}
      </body>
    </html>
  )
}